services:
  api:
    build:
      target: development
    volumes:
      - .:/app
      - ./import:/import
      - nuget_packages:/root/.nuget/packages
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  frontend:
    build:
      target: development
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  nuget_packages:
  frontend_node_modules:
